---

- name: "[POSTGRESQL] Restart PostgreSQL"
  service:
    name: postgresql
    state: restarted
  tags:
    - postgresql

- name: "[POSTGRESQL] Restart PostgreSQL"
  service:
    name: postgresql
    state: started
  tags:
    - postgresql
