from dtl.api.dtl_icao import airports_get, departures_get
from est.db.cur import con_cur
import json
from io import StringIO
import psycopg2
from psycopg2 import sql

###Not yet working; figuring out json data input with pop_table first

def wrt_airport(TableName):

    JsonDat = json.dumps(airports_get())
    print(JsonDat)

    cur, con = con_cur()
    try:
        cur.execute(
            sql.SQL("""CREATE TABLE {} (
                id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ingested_at timestamp DEFAULT CURRENT_TIMESTAMP,
                data json NOT NULL
            """).format(sql.Identifier(TableName)))
        cur.execute(
            sql.SQL("""COPY {} (data) FROM %s""")
                .format(sql.Identifier(TableName)), [JsonDat])
    except (Exception, psycopg2.DatabaseError) as error:
            print("Error: %s" % error)
            con.rollback()
            cur.close()
    con.commit()
    cur.close()
    