---
# tasks for Spark config steps

- name: "[SPARK] Set Spark configuration files"
  template:
    src: "{{ item }}.j2"
    dest: "/opt/spark-{{ spark_version }}-bin-hadoop2.7/conf/{{ item }}"
  with_items:
    - spark-env.sh
    - spark-defaults.conf
  notify:
    - "[SPARK] Restart Spark Master"
    - "[SPARK] Restart Spark Worker"
  tags:
    - spark
