---
# tasks file for land_search

- name: "[LANDSEARCH] Ensure group {{ ls_group }} exists"
  group:
    name: "{{ ls_group }}"
    state: present

- name: "[LANDSEARCH] Add all users to primary {{ ls_group }} group"
  user:
    name: "{{ item }}"
    group: "{{ ls_group }}"
    state: present
  with_items:
    - "hduser"
    - "ubuntu"
    - "postgres"

- name: "[LANDSEARCH] Add MBP key as authorized for {{ ls_user }} user"
  authorized_key:
    user: "{{ ls_user }}"
    key: "{{ lookup('file', '/Users/owenwilliams/.ssh/id_rsa.pub') }}"

- name: "[LANDSEARCH] Ensure land_search data directory exists"
  file:
    path: "{{ ls_data_dir }}"
    owner: "{{ ls_user }}"
    group: "{{ ls_group }}"
    state: directory
    mode: 0777

- name: "[LANDSEARCH] Git checkout"
  git:
    repo: 'https://github.com/owenmwilliams/land_search'
    dest: "{{ ls_data_dir }}"
    version: "{{ version }}"

- name: "[LANDSEARCH] Install required dev packages"
  apt:
    name: ['libgdal-dev', 'libffi-dev', 'libparquet-dev', 'libutf8proc-dev', 'libbz2-dev', 'liblz4-dev', 'libbrotli-dev', 'libsnappy-dev']
    state: latest

- name: "[LANDSEARCH] Ensure ~/.bashrc for {{ ls_user }} exports LSHOME"
  lineinfile:
    path: "/home/{{ ls_user }}/.bashrc"
    line: "{{ item }}"
  with_items:
    - "export LSHOME={{ ls_data_dir }}"
    - "export PATH=$PATH:$LSHOME"
    - "export CPLUS_INCLUDE_PATH=/usr/include/gdal"
    - "export C_INCLUDE_PATH=/usr/include/gdal"
    - "export PATH=$PATH:$CPLUS_INCLUDE_PATH:$C_INCLUDE_PATH"

- name: "[LANDSEARCH] Install specified python requirements"
  pip:
    requirements: "{{ ls_data_dir }}/requirements.txt"
    extra_args: "--no-cache-dir"
  environment: 
    PYARROW_CMAKE_OPTIONS: "-DARROW_ARMV8_ARCH=armv8-a -DCMAKE_INSTALL_PREFIX=$ARROW_HOME -DCMAKE_INSTALL_LIBDIR=lib -DARROW_PARQUET=ON -DARROW_HDFS=ON -DARROW_PYTHON=ON -DARROW_WITH_SNAPPY=ON -DARROW_WITH_BROTLI=ON -DARROW_WITH_LZ4=ON -DARROW_WITH_BZ2=ON"
    PYARROW_WITH_PARQUET: 1
    PYARROW_WITH_HDFS: 1
    ARROW_HOME: "/usr"
    ARROW_LIBHDFS_DIR: "/opt/hadoop-3.3.0/lib/native"
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-arm64/jre"
