---
# tasks file for postgresql

- name: "[POSTGRESQL] Ensure PostgreSQL data directory exists"
  file:
    path: "{{ postgresql_data_dir }}"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    state: directory
    mode: 0700

- name: "[POSTGRESQL] Configure pg_hba.conf PostgreSQL (Debian based)"
  copy:
    src: "pg_hba.conf"
    dest: "{{ postgresql_data_dir }}/pg_hba.conf"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
  when: ansible_os_family == "Debian"
  notify:
    - "[POSTGRESQL] Restart PostgreSQL"
  tags:
    - postgresql

- name: "[POSTGRESQL] Configure pg_hba.conf PostgreSQL (Debian based)"
  copy:
    src: "pg_hba.conf"
    dest: /etc/postgresql/12/main/pg_hba.conf
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
  when: ansible_os_family == "Debian"
  notify:
    - "[POSTGRESQL] Restart PostgreSQL"
  tags:
    - postgresql

- name: "[POSTGRESQL] Configure postgresql.conf PostgreSQL (Debian based)"
  lineinfile:
    path: "{{ postgresql_data_dir }}/postgresql.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"   
  with_items:
    - { regexp: '^listen_addresses =', line: "listen_addresses = '*'"}
    - { regexp: '^data_directory =', line: "data_directory = '{{ postgresql_data_dir }}'"}
  when: ansible_os_family == "Debian"
  notify:
    - "[POSTGRESQL] Restart PostgreSQL"
  tags:
    - postgresql

- name: "[POSTGRESQL] Configure postgresql.conf PostgreSQL (Debian based)"
  lineinfile:
    path: /etc/postgresql/12/main/postgresql.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"   
  with_items:
    - { regexp: '^listen_addresses =', line: "listen_addresses = '*'"}
    - { regexp: '^data_directory =', line: "data_directory = '{{ postgresql_data_dir }}'"}
  when: ansible_os_family == "Debian"
  notify:
    - "[POSTGRESQL] Restart PostgreSQL"
  tags:
    - postgresql

- name: "[POSTGRESQL] Ensure ~/.bashrc for hduser exports PGSQL_HOME"
  lineinfile:
    path: "/home/hduser/.bashrc"
    line: "{{ item }}"
  with_items:
    - "export PGSQL_HOME=/usr/lib/postgresql/12"
    - "export PATH=$PATH:$PGSQL_HOME/bin"

- name: "[POSTGRESQL] Add MBP key as authorized for postgres user"
  authorized_key:
    user: "{{ postgresql_user }}"
    key: "{{ lookup('file', '/Users/owenwilliams/.ssh/id_rsa.pub') }}"
