---
# tasks file for postgresql

- name: "[POSTGRESQL] Check if PostgreSQL database is initialized"
  stat:
    path: "{{ postgresql_data_dir }}/PG_VERSION"
  register: pgdata_dir_version

- name: "[POSTGRESQL] Ensure PostgreSQL database is initialized"
  command: "{{ postgresql_bin_path }}/initdb -D {{ postgresql_data_dir }}"
  when: not pgdata_dir_version.stat.exists
  become: true
  become_user: "{{ postgresql_user }}"
  vars:
    ansible_ssh_pipelining: true

- name: "[POSTGRESQL] Start PostgreSQL"
  service:
    name: postgresql@12-main
    state: started
  tags:
    - postgresql

- name: "[POSTGRESQL] Ensure land_search tablespace directory exists"
  file:
    path: "{{ postgresql_data_dir }}/land_search"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    state: directory
    mode: 0700

- name: "[POSTGRESQL] Create a new tablespace called land_search"
  become: true
  become_user: postgres  
  postgresql_tablespace:
    name: land_search
    owner: "{{ postgresql_user }}"
    location: "{{ postgresql_data_dir }}/land_search"

- name: "[POSTGRESQL] Create a new database with name original_dump"
  become: true
  become_user: postgres
  postgresql_db:
    name: original_dump
    tablespace: land_search

- name: "[POSTGRESQL] Adds postgis extension to the database original_dump"
  become: true
  become_user: postgres
  community.general.postgresql_ext:
    name: postgis
    db: original_dump
