---
# tasks for Spark config steps

- name: "[SPARK] Ensure ~/.bashrc for {{ hadoop_user }} exports SPARKHOME"
  lineinfile:
    path: "/home/{{ hadoop_user }}/.bashrc"
    line: "{{ item }}"
  with_items:
    - "export SPARK_HOME=/opt/spark-3.0.1-bin-hadoop2.7"
    - "export PATH=$PATH:$SPARK_HOME/bin"
    
- name: "[SPARK] Set Spark configuration files"
  template:
    src: "{{ item }}.j2"
    dest: "/opt/spark-{{ spark_version }}-bin-hadoop2.7/conf/{{ item }}"
  with_items:
    - spark-env.sh
    - spark-defaults.conf
  notify:
    - "[SPARK] Restart Spark Master"
    - "[SPARK] Restart Spark Worker"
  tags:
    - spark
