---
# Spark Master related tasks

- name: "[Spark] Set Spark Master unit file"
  template:
    src: "spark-master.service.j2"
    dest: /etc/systemd/system/spark-master.service
  notify:
    - "[SPARK] Resload systemd"
    - "[SPARK] Restart Spark Master"
  tags:
    - spark

- name: "[SPARK] Ensure Spark Master is started"
  service:
    name: spark-master
    state: started
    enabled: true
  tags:
    - spark
