---
# Spark Worker related tasks

- name: "[Spark] Set Spark Worker unit file"
  template:
    src: "spark-worker.service.j2"
    dest: /etc/systemd/system/spark-worker.service
  notify:
    - "[SPARK] Resload systemd"
    - "[SPARK] Restart Spark Worker"
  tags:
    - spark

- name: "[SPARK] Ensure Spark Worker is started"
  service:
    name: spark-worker
    state: started
    enabled: true
  tags:
    - spark
