---
# tasks file for land_search

# Ensure land_search directory exists
- name: Ensure land_search data directory exists.
  file:
    path: "{{ ls_data_dir }}"
    owner: "{{ ls_user }}"
    group: "{{ ls_group }}"
    state: directory
    mode: 0700

# Clone github repo
- name: Git checkout
  git:
    repo: 'https://github.com/owenmwilliams/land_search'
    dest: "{{ ls_data_dir }}"
    version: v0.1-alpha

# Install libgdal-dev
- name: Install libgdal-dev
  apt:
    name: libgdal-dev
    state: latest

# Add land_search directory and gdal_config to PATH
- name: "Ensure ~/.bashrc for {{ ls_user }} exports LSHOME"
  lineinfile:
    path: "/home/{{ ls_user }}/.bashrc"
    line: "{{ item }}"
  with_items:
    - "export LSHOME={{ ls_data_dir }}"
    - "export PATH=$PATH:$LSHOME"
    - "export CPLUS_INCLUDE_PATH=/usr/include/gdal"
    - "export C_INCLUDE_PATH=/usr/include/gdal"
    - "export PATH=$PATH:$CPLUS_INCLUDE_PATH:$C_INCLUDE_PATH"

# Install requirements from requirements file
- name: Install specified python requirements
  pip:
    requirements: "{{ ls_data_dir }}/requirements.txt"
